ccflags-y := -std=gnu99 -Wno-unused-variable -Wno-unused-function -Wno-vla
cc_kex-y += cckex.o net/filter.o chardev.o common.o cc/cchandler.o cc/ccmethod.o net/heur_filter.o net/dns.o net/tls.o net/connection_list.o net/tls_crypto.o net/websocket.o net/signal_message.o net/base64.o crypto/hmac/hmac_sha2.o crypto/hmac/sha2.o crypto/hkdf/hkdf.o signal/protobuf/protobuf.o
obj-m += cc_kex.o
