obj-$(CONFIG_CCKEX_MOD) += cc_kex.o

cc_kex-m := cckex.o net/filter.o chardev.o common.o cc/cchandler.o cc/ccmethod.o net/heur_filter.o net/dns.o net/tls.o net/connection_list.o net/tls_crypto.o net/websocket.o net/signal_message.o net/base64.o crypto/hmac/hmac_sha2.o crypto/hmac/sha2.o crypto/hkdf/hkdf.o signal/protobuf/protobuf.o
